/*
 * Ekstraksi Fitur Plat Kedaraan Bermotor Mahasiswa Fakultas Ilmu Komputer 
 * Universitas Muslim Indonsia Menggunakan Metode Gray Level Co-Occurrence Matrix 
 * (GLCM)
 * Oleh: Agus Arisandi
 */
package Plat;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author Administrator
 */
public class Fdatapemilik extends javax.swing.JFrame {

    /**
     * Creates new form Fdatapemilik
     */
    
    //Dekelarasi variabel public untuk database
    public Connection conn;
    public Statement cn;
    public byte x;

    public Fdatapemilik() {
        initComponents();
        normal ();
        tampildata();   
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnim = new javax.swing.JTextField();
        txtnma = new javax.swing.JTextField();
        txtanktn = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtalmt = new javax.swing.JTextArea();
        cb_jk = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtplat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nim");

        jLabel2.setText("Nama");

        jLabel3.setText("Angkatan");

        jLabel4.setText("Alamat");

        txtnim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnimKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnimKeyTyped(evt);
            }
        });

        txtnma.setEnabled(false);

        txtanktn.setEnabled(false);

        btnsimpan.setText("Simpan");
        btnsimpan.setEnabled(false);
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.setEnabled(false);
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nim", "Nama", "Angkatan", "Jenis Kelamin", "Alamat", "No Plat"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setText("Jenis Kelamin");

        txtalmt.setColumns(20);
        txtalmt.setRows(5);
        jScrollPane2.setViewportView(txtalmt);

        cb_jk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki-laki", "Perempuan", " " }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel6.setText("DATA PEMILIK");

        jLabel7.setText("No. Plat");

        txtplat.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnma, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtanktn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnim, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cb_jk, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(109, 109, 109))
                                    .addComponent(txtplat, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(231, 231, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 352, Short.MAX_VALUE)
                                .addComponent(btnsimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnhapus)
                                .addGap(18, 18, 18)
                                .addComponent(btnkeluar)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(537, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtanktn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cb_jk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtplat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan)
                    .addComponent(btnhapus)
                    .addComponent(btnkeluar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnimKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            try{
                koneksi();
                String sql="Select * from tblpemilik where " +
                "nim='" + txtnim.getText() + "'";
                ResultSet rs=cn.executeQuery(sql);
                if(rs.next()){
                    txtnma.setText(rs.getString("nama"));
                    cb_jk.addItem(rs.getString("jeniskelamin"));
                    txtanktn.setText(rs.getString(3));
                    txtalmt.setText(rs.getString("alamat"));
                    txtplat.setText(rs.getString("noplat"));
                    txtnim.setEnabled(false);
                    txtnma.setEnabled(true);
                    txtplat.setEnabled(true);
                    txtanktn.setEnabled(true);
                    cb_jk.setEnabled(true);
                    txtalmt.setEnabled(true);
                    btnsimpan.setEnabled(true);
                    btnsimpan.setText("Update");
                    btnhapus.setEnabled(true);
                    x=1;
                }else{
                    txtnma.setText("");
                    txtanktn.setText("");
                    txtalmt.setText("");
                    txtplat.setText("");
                    txtnma.setEnabled(true);
                    txtanktn.setEnabled(true);
                    txtplat.setEnabled(true);
                    cb_jk.setEnabled(true);
                    txtalmt.setEnabled(true);
                    txtnma.requestFocus();
                    btnsimpan.setEnabled(true);
                    btnsimpan.setText("Simpan");
                    btnhapus.setEnabled(false);
                    x=0;
                }
            }catch (Exception e){}
        }
    }//GEN-LAST:event_txtnimKeyPressed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        if (x==0){
            try{
                koneksi();
                String perintahSQL="INSERT INTO tblpemilik values ("
                + "'" + txtnim.getText() + "',"
                + "'" + txtnma.getText() + "',"
                + "'" + txtanktn.getText() + "',"
                + "'" + cb_jk.getSelectedItem() + "',"
                + "'" + txtalmt.getText() + "',"
                + "'" + txtplat.getText() + "'"
                + ")";
                cn.executeUpdate(perintahSQL);
                conn.close();
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                tampildata();
                normal();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Maaf, " +
                    "Proses penyimpanan data gagal");
            }
        }else{
            try{
                koneksi();
                String perintahSQL="update tblpemilik set"
                + " nama = '" + txtnma.getText() + "',"
                + " angkatan = '" + txtanktn.getText() + "',"
                + " jeniskelamin = '" + cb_jk.getSelectedItem() + "',"
                + " alamat = '" + txtalmt.getText() + "',"
                + " noplat = '" + txtplat.getText() + "' where"
                + " nim = '" + txtnim.getText() +  "'";

                cn.executeUpdate(perintahSQL);
                conn.close();
                JOptionPane.showMessageDialog(null, "Proses " +
                    "Update berhasil");
                tampildata();
                normal();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Maaf, " +
                    "Proses Update data gagal");
            }
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        txtnim.requestFocus();
        txtnim.setText("");
        this.dispose();
        Home a = new Home();  
        a.setVisible(true); 

    }//GEN-LAST:event_btnkeluarActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        String[] Opsi = {"Ya'","Tidak'"};
        int Pilih = JOptionPane.showOptionDialog(null,"Yakin Anda akan " +
            "menghapus data ini...?",
            "Pertanyaan",JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,null,Opsi,Opsi[0]);
        if(Pilih == JOptionPane.YES_OPTION){
            try{
                koneksi();
                String perintahSQL="DELETE FROM tblpemilik WHERE " +
                "nim='" + txtnim.getText() + "'";
                cn.executeUpdate(perintahSQL);
                conn.close();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                tampildata();
                normal();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Maaf, " +
                    "Proses penghapusan data gagal");
            }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int t=jTable1.getSelectedRow();
        txtnim.setText(jTable1.getValueAt(t, 0).toString());
        txtnma.setText(jTable1.getValueAt(t, 1).toString());
        txtanktn.setText(jTable1.getValueAt(t, 2).toString());
        cb_jk.addItem(jTable1.getValueAt(t, 3).toString());
        txtalmt.setText(jTable1.getValueAt(t, 4).toString());
        txtplat.setText(jTable1.getValueAt(t, 5).toString());
        txtnim.setEnabled(false);
        txtnma.setEnabled(true);
        txtanktn.setEnabled(true);
        cb_jk.setEnabled(true);
        txtalmt.setEnabled(true);
        txtplat.setEnabled(true);
        txtnma.requestFocus();
        btnsimpan.setEnabled(true);
        btnhapus.setEnabled(true);
        btnsimpan.setText("Update");
    }//GEN-LAST:event_jTable1MouseClicked

private void txtnimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnimKeyTyped
// TODO add your handling code here:
    char karakter = evt.getKeyChar();
    if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
    getToolkit().beep();
    evt.consume();
}
}//GEN-LAST:event_txtnimKeyTyped
    public void normal(){
            txtnim.setEnabled(true);
            txtalmt.setEnabled(false);
            cb_jk.setEnabled(false);
            txtanktn.setEnabled(false);
            txtnma.setEnabled(false);
            txtplat.setEnabled(false);
            txtalmt.setText("");
            txtnma.setText("");
            txtanktn.setText("");
            txtplat.setText("");
            btnsimpan.setEnabled(false);
            btnhapus.setEnabled(false);
            txtnim.requestFocus();
            txtnim.setText("");
    }

    public void koneksi(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql:" +
            "//localhost:3306/dbappplat","root","");
            cn=conn.createStatement();
        }catch (Exception e){
        JOptionPane.showMessageDialog(null,"koneksi gagal..");
        System.out.println(e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fdatapemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fdatapemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fdatapemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fdatapemilik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fdatapemilik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JComboBox cb_jk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea txtalmt;
    private javax.swing.JTextField txtanktn;
    private javax.swing.JTextField txtnim;
    private javax.swing.JTextField txtnma;
    private javax.swing.JTextField txtplat;
    // End of variables declaration//GEN-END:variables

 private void tampildata() {
        DefaultTableModel tblmhs=new DefaultTableModel();
        tblmhs.addColumn("Nim");
        tblmhs.addColumn("Nama");
        tblmhs.addColumn("Angkatan");
        tblmhs.addColumn("Jenis Kelamin");
        tblmhs.addColumn("Alamat");
        tblmhs.addColumn("No Plat");
    
        try{
            koneksi();
            String sql="select * from tblpemilik order by nim asc";
            ResultSet rs=cn.executeQuery(sql);
            while(rs.next()){
                tblmhs.addRow(new Object[]{
                rs.getString(1),rs.getString(2),
                rs.getString(3),rs.getString(4),
                rs.getString(5),rs.getString(6)});
            }
            jTable1.setModel(tblmhs);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Ada " +
                    "kesalahan menampilkan data di tabel");
        }
    
 }}
